# Generated by Django 6.0 on 2025-12-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=124)),
                ('profession', models.CharField(max_length=124)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=124)),
                ('street', models.CharField(max_length=124)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=124, null=True)),
                ('neighborhood', models.CharField(max_length=124)),
                ('city', models.CharField(max_length=124)),
            ],
            options={
                'verbose_name': 'Professional',
                'verbose_name_plural': 'Professionals',
                'ordering': ['social_name'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=124)),
                ('scheduled_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.professional')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
